name: CI

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  phpunit:
    name: PHPUnit on ${{ matrix.php-version }} ${{ matrix.composer-flags }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php-version:
          - "8.0"
          - "8.1"
          - "8.2"
        composer-flags:
          - ""
          - "--prefer-lowest"

    steps:
    - uses: actions/checkout@v3

    - uses: shivammathur/setup-php@v2
      with:
          php-version: ${{ matrix.php-version }}
          coverage: pcov
          tools: composer

    - name: Install dependencies
      run: composer update --no-progress ${{ matrix.composer-flags }}

    - name: Run test suite
      run: ./vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover
